[package]
name = "financial-smart-contract"
version = "0.1.0"

[dependencies]
pwasm-std = "0.13"
pwasm-ethereum = "0.8"
pwasm-abi = "0.2"
pwasm-abi-derive = "0.2"
lazy_static = { version = "1.2.0", features = ["spin_no_std"] }

[dev-dependencies.pwasm-test]
git = "https://github.com/paritytech/pwasm-test"
default-features = false

[lib]
# Replace ${crate-type} with 'cdylib' for building, 'lib' for testing
# (as cdylib cannot be tested, but we don't need any cdylib functionality for testing)
crate-type = ["${crate-type}"]

[features]
std = ["pwasm-std/std", "pwasm-ethereum/std", "pwasm-test/std"]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
